#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=runtime_password="$ACTIONGATE_DB_PASSWORD" <<'SQL'
CREATE ROLE actiongate LOGIN PASSWORD :'runtime_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO actiongate;
GRANT CONNECT ON DATABASE actiongate TO actiongate;
ALTER DEFAULT PRIVILEGES FOR ROLE actiongate_owner IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO actiongate;
ALTER DEFAULT PRIVILEGES FOR ROLE actiongate_owner IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO actiongate;
SQL
